// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sprawl.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_OPEN   State = 0
	State_LOCKED State = 1
)

var State_name = map[int32]string{
	0: "OPEN",
	1: "LOCKED",
}

var State_value = map[string]int32{
	"OPEN":   0,
	"LOCKED": 1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{0}
}

type Operation int32

const (
	Operation_CREATE Operation = 0
	Operation_DELETE Operation = 1
	Operation_LOCK   Operation = 2
	Operation_UNLOCK Operation = 3
	Operation_SYNC   Operation = 4
	Operation_PING   Operation = 5
	Operation_PONG   Operation = 6
)

var Operation_name = map[int32]string{
	0: "CREATE",
	1: "DELETE",
	2: "LOCK",
	3: "UNLOCK",
	4: "SYNC",
	5: "PING",
	6: "PONG",
}

var Operation_value = map[string]int32{
	"CREATE": 0,
	"DELETE": 1,
	"LOCK":   2,
	"UNLOCK": 3,
	"SYNC":   4,
	"PING":   5,
	"PONG":   6,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{1}
}

type Order struct {
	Id                   []byte               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Asset                string               `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	CounterAsset         string               `protobuf:"bytes,4,opt,name=counterAsset,proto3" json:"counterAsset,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                float32              `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	State                State                `protobuf:"varint,7,opt,name=state,proto3,enum=pb.State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Order) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Order) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Order) GetCounterAsset() string {
	if m != nil {
		return m.CounterAsset
	}
	return ""
}

func (m *Order) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetState() State {
	if m != nil {
		return m.State
	}
	return State_OPEN
}

type OrderList struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderList) Reset()         { *m = OrderList{} }
func (m *OrderList) String() string { return proto.CompactTextString(m) }
func (*OrderList) ProtoMessage()    {}
func (*OrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{1}
}

func (m *OrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderList.Unmarshal(m, b)
}
func (m *OrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderList.Marshal(b, m, deterministic)
}
func (m *OrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderList.Merge(m, src)
}
func (m *OrderList) XXX_Size() int {
	return xxx_messageInfo_OrderList.Size(m)
}
func (m *OrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderList proto.InternalMessageInfo

func (m *OrderList) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Channel struct {
	Id                   []byte          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options              *ChannelOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{2}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Channel) GetOptions() *ChannelOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ChannelList struct {
	Channels             []*Channel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChannelList) Reset()         { *m = ChannelList{} }
func (m *ChannelList) String() string { return proto.CompactTextString(m) }
func (*ChannelList) ProtoMessage()    {}
func (*ChannelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{3}
}

func (m *ChannelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelList.Unmarshal(m, b)
}
func (m *ChannelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelList.Marshal(b, m, deterministic)
}
func (m *ChannelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelList.Merge(m, src)
}
func (m *ChannelList) XXX_Size() int {
	return xxx_messageInfo_ChannelList.Size(m)
}
func (m *ChannelList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelList.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelList proto.InternalMessageInfo

func (m *ChannelList) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Recipient struct {
	PeerID               []byte   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipient) Reset()         { *m = Recipient{} }
func (m *Recipient) String() string { return proto.CompactTextString(m) }
func (*Recipient) ProtoMessage()    {}
func (*Recipient) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{4}
}

func (m *Recipient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipient.Unmarshal(m, b)
}
func (m *Recipient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipient.Marshal(b, m, deterministic)
}
func (m *Recipient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipient.Merge(m, src)
}
func (m *Recipient) XXX_Size() int {
	return xxx_messageInfo_Recipient.Size(m)
}
func (m *Recipient) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipient.DiscardUnknown(m)
}

var xxx_messageInfo_Recipient proto.InternalMessageInfo

func (m *Recipient) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type WireMessage struct {
	ChannelID            []byte    `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Operation            Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=pb.Operation" json:"operation,omitempty"`
	Sender               []byte    `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data                 []byte    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WireMessage) Reset()         { *m = WireMessage{} }
func (m *WireMessage) String() string { return proto.CompactTextString(m) }
func (*WireMessage) ProtoMessage()    {}
func (*WireMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{5}
}

func (m *WireMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireMessage.Unmarshal(m, b)
}
func (m *WireMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireMessage.Marshal(b, m, deterministic)
}
func (m *WireMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireMessage.Merge(m, src)
}
func (m *WireMessage) XXX_Size() int {
	return xxx_messageInfo_WireMessage.Size(m)
}
func (m *WireMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WireMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WireMessage proto.InternalMessageInfo

func (m *WireMessage) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

func (m *WireMessage) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_CREATE
}

func (m *WireMessage) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *WireMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRequest struct {
	ChannelID            []byte   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	CounterAsset         string   `protobuf:"bytes,3,opt,name=counterAsset,proto3" json:"counterAsset,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{6}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

func (m *CreateRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *CreateRequest) GetCounterAsset() string {
	if m != nil {
		return m.CounterAsset
	}
	return ""
}

func (m *CreateRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type JoinRequest struct {
	Asset                string   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	CounterAsset         string   `protobuf:"bytes,2,opt,name=counterAsset,proto3" json:"counterAsset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{7}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *JoinRequest) GetCounterAsset() string {
	if m != nil {
		return m.CounterAsset
	}
	return ""
}

type ChannelOptions struct {
	AssetPair            string   `protobuf:"bytes,1,opt,name=assetPair,proto3" json:"assetPair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelOptions) Reset()         { *m = ChannelOptions{} }
func (m *ChannelOptions) String() string { return proto.CompactTextString(m) }
func (*ChannelOptions) ProtoMessage()    {}
func (*ChannelOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{8}
}

func (m *ChannelOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelOptions.Unmarshal(m, b)
}
func (m *ChannelOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelOptions.Marshal(b, m, deterministic)
}
func (m *ChannelOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelOptions.Merge(m, src)
}
func (m *ChannelOptions) XXX_Size() int {
	return xxx_messageInfo_ChannelOptions.Size(m)
}
func (m *ChannelOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelOptions proto.InternalMessageInfo

func (m *ChannelOptions) GetAssetPair() string {
	if m != nil {
		return m.AssetPair
	}
	return ""
}

type OrderSpecificRequest struct {
	OrderID              []byte   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	ChannelID            []byte   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderSpecificRequest) Reset()         { *m = OrderSpecificRequest{} }
func (m *OrderSpecificRequest) String() string { return proto.CompactTextString(m) }
func (*OrderSpecificRequest) ProtoMessage()    {}
func (*OrderSpecificRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{9}
}

func (m *OrderSpecificRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSpecificRequest.Unmarshal(m, b)
}
func (m *OrderSpecificRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSpecificRequest.Marshal(b, m, deterministic)
}
func (m *OrderSpecificRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSpecificRequest.Merge(m, src)
}
func (m *OrderSpecificRequest) XXX_Size() int {
	return xxx_messageInfo_OrderSpecificRequest.Size(m)
}
func (m *OrderSpecificRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSpecificRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSpecificRequest proto.InternalMessageInfo

func (m *OrderSpecificRequest) GetOrderID() []byte {
	if m != nil {
		return m.OrderID
	}
	return nil
}

func (m *OrderSpecificRequest) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

type ChannelSpecificRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelSpecificRequest) Reset()         { *m = ChannelSpecificRequest{} }
func (m *ChannelSpecificRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelSpecificRequest) ProtoMessage()    {}
func (*ChannelSpecificRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{10}
}

func (m *ChannelSpecificRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelSpecificRequest.Unmarshal(m, b)
}
func (m *ChannelSpecificRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelSpecificRequest.Marshal(b, m, deterministic)
}
func (m *ChannelSpecificRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelSpecificRequest.Merge(m, src)
}
func (m *ChannelSpecificRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelSpecificRequest.Size(m)
}
func (m *ChannelSpecificRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelSpecificRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelSpecificRequest proto.InternalMessageInfo

func (m *ChannelSpecificRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type CreateResponse struct {
	CreatedOrder         *Order   `protobuf:"bytes,1,opt,name=createdOrder,proto3" json:"createdOrder,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{11}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreatedOrder() *Order {
	if m != nil {
		return m.CreatedOrder
	}
	return nil
}

func (m *CreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type JoinResponse struct {
	JoinedChannel        *Channel `protobuf:"bytes,1,opt,name=joinedChannel,proto3" json:"joinedChannel,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{12}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetJoinedChannel() *Channel {
	if m != nil {
		return m.JoinedChannel
	}
	return nil
}

func (m *JoinResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GenericResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{13}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{14}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5e409e9578376a3, []int{15}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.State", State_name, State_value)
	proto.RegisterEnum("pb.Operation", Operation_name, Operation_value)
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*OrderList)(nil), "pb.OrderList")
	proto.RegisterType((*Channel)(nil), "pb.Channel")
	proto.RegisterType((*ChannelList)(nil), "pb.ChannelList")
	proto.RegisterType((*Recipient)(nil), "pb.Recipient")
	proto.RegisterType((*WireMessage)(nil), "pb.WireMessage")
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*JoinRequest)(nil), "pb.JoinRequest")
	proto.RegisterType((*ChannelOptions)(nil), "pb.ChannelOptions")
	proto.RegisterType((*OrderSpecificRequest)(nil), "pb.OrderSpecificRequest")
	proto.RegisterType((*ChannelSpecificRequest)(nil), "pb.ChannelSpecificRequest")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterType((*JoinResponse)(nil), "pb.JoinResponse")
	proto.RegisterType((*GenericResponse)(nil), "pb.GenericResponse")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

func init() { proto.RegisterFile("sprawl.proto", fileDescriptor_b5e409e9578376a3) }

var fileDescriptor_b5e409e9578376a3 = []byte{
	// 833 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x66, 0x15, 0x4b, 0x8e, 0x8f, 0x15, 0xc7, 0x2c, 0x9d, 0x8e, 0xc6, 0x03, 0x53, 0x23, 0x2e,
	0x10, 0xa5, 0x38, 0x83, 0xa1, 0x94, 0xdb, 0x8c, 0xa3, 0x31, 0x05, 0x63, 0x67, 0x36, 0xe9, 0x74,
	0xb8, 0x43, 0x96, 0x4e, 0x83, 0x40, 0x96, 0xc4, 0x6a, 0x03, 0xc3, 0x3d, 0xaf, 0xc0, 0x13, 0xf1,
	0x0e, 0x5c, 0xf0, 0x34, 0xcc, 0xfe, 0x48, 0x96, 0x5c, 0x9a, 0x42, 0xef, 0xf6, 0x7c, 0xe7, 0x77,
	0xbf, 0xf3, 0xad, 0x04, 0x6e, 0x55, 0xf2, 0xe8, 0xd7, 0x6c, 0x56, 0xf2, 0x42, 0x14, 0xd4, 0x2a,
	0xb7, 0x93, 0x07, 0x37, 0x45, 0x71, 0x93, 0xe1, 0x99, 0x42, 0xb6, 0xb7, 0x2f, 0xce, 0x44, 0xba,
	0xc3, 0x4a, 0x44, 0xbb, 0x52, 0x07, 0xf9, 0x7f, 0x11, 0xb0, 0x37, 0x3c, 0x41, 0x4e, 0x47, 0x60,
	0xa5, 0x89, 0x47, 0xa6, 0x24, 0x70, 0x99, 0x95, 0x26, 0xf4, 0x73, 0xe8, 0xc7, 0x1c, 0x23, 0x81,
	0x89, 0x67, 0x4d, 0x49, 0x30, 0x9c, 0x4f, 0x66, 0xba, 0xd8, 0xac, 0x2e, 0x36, 0xbb, 0xae, 0x8b,
	0xb1, 0x3a, 0x94, 0xde, 0x03, 0x3b, 0xaa, 0x2a, 0x14, 0xde, 0xd1, 0x94, 0x04, 0x03, 0xa6, 0x0d,
	0xea, 0x83, 0x1b, 0x17, 0xb7, 0xb9, 0x40, 0x7e, 0xae, 0x9c, 0x3d, 0xe5, 0xec, 0x60, 0xf4, 0x3e,
	0x38, 0xd1, 0x4e, 0x02, 0x9e, 0x3d, 0x25, 0x41, 0x8f, 0x19, 0x4b, 0x56, 0x2c, 0x79, 0x1a, 0xa3,
	0xe7, 0x4c, 0x49, 0x60, 0x31, 0x6d, 0xd0, 0x07, 0x60, 0x57, 0x22, 0x12, 0xe8, 0xf5, 0xa7, 0x24,
	0x18, 0xcd, 0x07, 0xb3, 0x72, 0x3b, 0xbb, 0x92, 0x00, 0xd3, 0xb8, 0x3f, 0x83, 0x81, 0xba, 0xd7,
	0x2a, 0xad, 0x04, 0x7d, 0x1f, 0x9c, 0x42, 0x1a, 0x95, 0x47, 0xa6, 0x47, 0xc1, 0x50, 0x87, 0x2b,
	0x37, 0x33, 0x0e, 0x7f, 0x09, 0xfd, 0xc5, 0x0f, 0x51, 0x9e, 0x63, 0xf6, 0x12, 0x13, 0x8f, 0xa0,
	0x5f, 0x94, 0x22, 0x2d, 0xf2, 0xca, 0x30, 0x41, 0x65, 0xba, 0x89, 0xde, 0x68, 0x0f, 0xab, 0x43,
	0xfc, 0x2f, 0x60, 0x68, 0x5c, 0xaa, 0xf5, 0x87, 0x70, 0x1c, 0x6b, 0xb3, 0x6e, 0x3e, 0x6c, 0x65,
	0xb3, 0xc6, 0xe9, 0x7f, 0x00, 0x03, 0x86, 0x71, 0x5a, 0xa6, 0x98, 0x2b, 0x32, 0x4a, 0x44, 0xfe,
	0xf4, 0xc2, 0x8c, 0x61, 0x2c, 0xff, 0x77, 0x02, 0xc3, 0xe7, 0x29, 0xc7, 0x6f, 0xb1, 0xaa, 0xa2,
	0x1b, 0xa4, 0xef, 0xc2, 0xc0, 0x14, 0x68, 0x42, 0xf7, 0x00, 0xfd, 0x18, 0x06, 0x45, 0x89, 0x3c,
	0x92, 0x83, 0xa9, 0xd1, 0x47, 0xf3, 0x13, 0x75, 0xf3, 0x1a, 0x64, 0x7b, 0xbf, 0x6c, 0x59, 0x61,
	0x9e, 0x20, 0x57, 0xab, 0x73, 0x99, 0xb1, 0x28, 0x85, 0x5e, 0x12, 0x89, 0x48, 0xed, 0xcc, 0x65,
	0xea, 0xec, 0xff, 0x41, 0xe0, 0x64, 0xa1, 0x36, 0xce, 0xf0, 0xe7, 0x5b, 0xac, 0xc4, 0x6b, 0x06,
	0x69, 0x54, 0x61, 0xdd, 0xa5, 0x8a, 0xa3, 0x3b, 0x55, 0xd1, 0xfb, 0x77, 0x55, 0xd8, 0x2d, 0x55,
	0xf8, 0x4b, 0x18, 0x7e, 0x5d, 0xa4, 0x79, 0x3d, 0x54, 0xd3, 0x96, 0xdc, 0xd5, 0xd6, 0x7a, 0xb9,
	0xad, 0x3f, 0x83, 0x51, 0x77, 0xbf, 0xf2, 0x82, 0x2a, 0xfd, 0x32, 0x4a, 0xb9, 0xa9, 0xb7, 0x07,
	0xfc, 0x35, 0xdc, 0x53, 0x72, 0xba, 0x2a, 0x31, 0x4e, 0x5f, 0xa4, 0x71, 0x3d, 0x81, 0x07, 0x7d,
	0xa5, 0xaf, 0x86, 0x94, 0xda, 0xec, 0x12, 0x66, 0x1d, 0x10, 0xe6, 0x07, 0x70, 0xdf, 0xf4, 0x3f,
	0xac, 0x78, 0x20, 0x4e, 0xff, 0x7b, 0x18, 0xd5, 0x9b, 0xa8, 0xca, 0x22, 0xaf, 0x90, 0x7e, 0x02,
	0xae, 0x79, 0x8d, 0x6a, 0x24, 0x15, 0xdb, 0x91, 0x7c, 0xc7, 0x2d, 0x5f, 0x12, 0x72, 0x5e, 0x70,
	0xa3, 0x6d, 0x15, 0x17, 0x4a, 0x80, 0x69, 0xdc, 0xdf, 0x82, 0xab, 0x49, 0x35, 0xf5, 0x3f, 0x85,
	0x93, 0x1f, 0x8b, 0x34, 0xc7, 0xc4, 0x4c, 0x68, 0x1a, 0x74, 0x64, 0xdd, 0x8d, 0x78, 0x7d, 0x8f,
	0x39, 0x9c, 0x2e, 0x31, 0x47, 0x2e, 0xef, 0x69, 0xda, 0x34, 0x39, 0xe4, 0x15, 0x39, 0x8f, 0xc1,
	0x56, 0xb6, 0x54, 0x68, 0x5c, 0x24, 0x68, 0xb6, 0xa2, 0xce, 0x92, 0xf8, 0x9d, 0x7e, 0x23, 0x66,
	0xbf, 0xb5, 0xe9, 0xf7, 0xc1, 0x0e, 0x77, 0xa5, 0xf8, 0xed, 0xe1, 0x7b, 0x60, 0xab, 0x2f, 0x06,
	0x3d, 0x86, 0xde, 0xe6, 0x32, 0x5c, 0x8f, 0xdf, 0xa2, 0x00, 0xce, 0x6a, 0xb3, 0xf8, 0x26, 0xbc,
	0x18, 0x93, 0x87, 0xcf, 0x61, 0xd0, 0xbc, 0x13, 0xe9, 0x58, 0xb0, 0xf0, 0xfc, 0x3a, 0xd4, 0x41,
	0x17, 0xe1, 0x2a, 0xbc, 0x0e, 0xc7, 0x44, 0xa6, 0xca, 0x84, 0xb1, 0x25, 0xd1, 0x67, 0x6b, 0x75,
	0x3e, 0x92, 0xe8, 0xd5, 0x77, 0xeb, 0xc5, 0xb8, 0x27, 0x4f, 0x97, 0x4f, 0xd7, 0xcb, 0xb1, 0xad,
	0x4e, 0x9b, 0xf5, 0x72, 0xec, 0xcc, 0xff, 0xb4, 0xc0, 0x55, 0xd4, 0x7f, 0x15, 0xe5, 0x49, 0x86,
	0x9c, 0x9e, 0x81, 0xa3, 0x57, 0x48, 0xdf, 0x56, 0x1c, 0xb6, 0x1f, 0xd6, 0x84, 0xb6, 0x21, 0x43,
	0xcd, 0x13, 0x70, 0x2e, 0x30, 0x43, 0x81, 0xd4, 0x6b, 0xb6, 0x7a, 0xa0, 0x93, 0xc9, 0x3b, 0xd2,
	0x73, 0xc8, 0xe9, 0x63, 0xe8, 0xad, 0x8a, 0xf8, 0xa7, 0xff, 0x9b, 0xf6, 0x04, 0x9c, 0x67, 0x79,
	0xf6, 0x06, 0x89, 0x67, 0x70, 0xbc, 0x44, 0xa1, 0x75, 0xf6, 0xea, 0xd4, 0xbd, 0x34, 0x69, 0x00,
	0xee, 0x12, 0xc5, 0x79, 0x96, 0x29, 0xb3, 0xa2, 0x7a, 0xeb, 0x72, 0x5d, 0x93, 0x93, 0x26, 0x4a,
	0x7e, 0x57, 0xe7, 0x7f, 0x93, 0xe6, 0x89, 0xd6, 0x3c, 0x7e, 0x04, 0x3d, 0x29, 0x54, 0x7a, 0x2a,
	0x23, 0x5b, 0xdf, 0x81, 0xc9, 0x78, 0x0f, 0x98, 0xc1, 0xbe, 0x04, 0x7b, 0x85, 0xd1, 0x2f, 0x48,
	0x27, 0x2d, 0xd5, 0xfe, 0x47, 0x0a, 0x61, 0x89, 0xa2, 0x16, 0xf6, 0x5d, 0xe9, 0xed, 0x07, 0x41,
	0x1f, 0xc1, 0x48, 0x5f, 0xcc, 0x00, 0x9d, 0xab, 0x9d, 0xb6, 0x22, 0xe5, 0xe5, 0xb6, 0x8e, 0xfa,
	0xc5, 0x7e, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xe3, 0xb4, 0x08, 0xd1, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderHandlerClient is the client API for OrderHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderHandlerClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	Lock(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	Unlock(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetOrder(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*Order, error)
	GetAllOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrderList, error)
}

type orderHandlerClient struct {
	cc *grpc.ClientConn
}

func NewOrderHandlerClient(cc *grpc.ClientConn) OrderHandlerClient {
	return &orderHandlerClient{cc}
}

func (c *orderHandlerClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderHandlerClient) Delete(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderHandlerClient) Lock(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderHandlerClient) Unlock(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderHandlerClient) GetOrder(ctx context.Context, in *OrderSpecificRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderHandlerClient) GetAllOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrderList, error) {
	out := new(OrderList)
	err := c.cc.Invoke(ctx, "/pb.OrderHandler/GetAllOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderHandlerServer is the server API for OrderHandler service.
type OrderHandlerServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *OrderSpecificRequest) (*GenericResponse, error)
	Lock(context.Context, *OrderSpecificRequest) (*GenericResponse, error)
	Unlock(context.Context, *OrderSpecificRequest) (*GenericResponse, error)
	GetOrder(context.Context, *OrderSpecificRequest) (*Order, error)
	GetAllOrders(context.Context, *Empty) (*OrderList, error)
}

// UnimplementedOrderHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedOrderHandlerServer struct {
}

func (*UnimplementedOrderHandlerServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedOrderHandlerServer) Delete(ctx context.Context, req *OrderSpecificRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedOrderHandlerServer) Lock(ctx context.Context, req *OrderSpecificRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedOrderHandlerServer) Unlock(ctx context.Context, req *OrderSpecificRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedOrderHandlerServer) GetOrder(ctx context.Context, req *OrderSpecificRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedOrderHandlerServer) GetAllOrders(ctx context.Context, req *Empty) (*OrderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOrders not implemented")
}

func RegisterOrderHandlerServer(s *grpc.Server, srv OrderHandlerServer) {
	s.RegisterService(&_OrderHandler_serviceDesc, srv)
}

func _OrderHandler_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderHandler_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).Delete(ctx, req.(*OrderSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderHandler_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).Lock(ctx, req.(*OrderSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderHandler_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).Unlock(ctx, req.(*OrderSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderHandler_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).GetOrder(ctx, req.(*OrderSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderHandler_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderHandler/GetAllOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).GetAllOrders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderHandler",
	HandlerType: (*OrderHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderHandler_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OrderHandler_Delete_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _OrderHandler_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _OrderHandler_Unlock_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderHandler_GetOrder_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _OrderHandler_GetAllOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sprawl.proto",
}

// ChannelHandlerClient is the client API for ChannelHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelHandlerClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Leave(ctx context.Context, in *ChannelSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetChannel(ctx context.Context, in *ChannelSpecificRequest, opts ...grpc.CallOption) (*Channel, error)
	GetAllChannels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChannelList, error)
}

type channelHandlerClient struct {
	cc *grpc.ClientConn
}

func NewChannelHandlerClient(cc *grpc.ClientConn) ChannelHandlerClient {
	return &channelHandlerClient{cc}
}

func (c *channelHandlerClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/pb.ChannelHandler/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelHandlerClient) Leave(ctx context.Context, in *ChannelSpecificRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/pb.ChannelHandler/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelHandlerClient) GetChannel(ctx context.Context, in *ChannelSpecificRequest, opts ...grpc.CallOption) (*Channel, error) {
	out := new(Channel)
	err := c.cc.Invoke(ctx, "/pb.ChannelHandler/GetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelHandlerClient) GetAllChannels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChannelList, error) {
	out := new(ChannelList)
	err := c.cc.Invoke(ctx, "/pb.ChannelHandler/GetAllChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelHandlerServer is the server API for ChannelHandler service.
type ChannelHandlerServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Leave(context.Context, *ChannelSpecificRequest) (*GenericResponse, error)
	GetChannel(context.Context, *ChannelSpecificRequest) (*Channel, error)
	GetAllChannels(context.Context, *Empty) (*ChannelList, error)
}

// UnimplementedChannelHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedChannelHandlerServer struct {
}

func (*UnimplementedChannelHandlerServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedChannelHandlerServer) Leave(ctx context.Context, req *ChannelSpecificRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (*UnimplementedChannelHandlerServer) GetChannel(ctx context.Context, req *ChannelSpecificRequest) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (*UnimplementedChannelHandlerServer) GetAllChannels(ctx context.Context, req *Empty) (*ChannelList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllChannels not implemented")
}

func RegisterChannelHandlerServer(s *grpc.Server, srv ChannelHandlerServer) {
	s.RegisterService(&_ChannelHandler_serviceDesc, srv)
}

func _ChannelHandler_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelHandlerServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChannelHandler/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelHandlerServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelHandler_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelHandlerServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChannelHandler/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelHandlerServer).Leave(ctx, req.(*ChannelSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelHandler_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelHandlerServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChannelHandler/GetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelHandlerServer).GetChannel(ctx, req.(*ChannelSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelHandler_GetAllChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelHandlerServer).GetAllChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChannelHandler/GetAllChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelHandlerServer).GetAllChannels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChannelHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChannelHandler",
	HandlerType: (*ChannelHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _ChannelHandler_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _ChannelHandler_Leave_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _ChannelHandler_GetChannel_Handler,
		},
		{
			MethodName: "GetAllChannels",
			Handler:    _ChannelHandler_GetAllChannels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sprawl.proto",
}
